Eng newsletter 2020-12
cosmos/cosmos.network pull request #129
Opened 2020-12-10 21:12 UTC by lovincyrus

2020-12-11 00:06 UTC, nassdonald requested changes
Let's remove the cover images from the engineering newsletter, since they're always going to be the same. Let's just display the text for each "card" - it's much cleaner.

![image](https://user-images.githubusercontent.com/2961244/101844601-b971f400-3b44-11eb-9b7e-fc5560275f9b.png)

2020-12-11 00:41 UTC, lovincyrus commented
> Let's remove the cover images from the engineering newsletter, since they're always going to be the same. Let's just display the text for each "card" - it's much cleaner.

Should we just stick to 
![image](https://user-images.githubusercontent.com/1021101/101846728-7002b400-3b06-11eb-8b0c-e821b674a1df.png)

I wouldn't want to mess up other pages that are using the same component.

2020-12-11 15:34 UTC, nassdonald commented
If we’re worried about breaking things across the site because we’ve removed a few images on one page, we’re doing something wrong! 😛  This should do the trick:

Introduce an `image` prop to `TmCardHz` component and add a `v-if` to the image container. This will not break other instances of this component, because they will default to `true`.

2020-12-14 11:42 UTC, nassdonald approved these changes

2020-12-16 23:12 UTC, merged